- src/components/Product/Card/__tests__/index.test.tsx
- src/components/Product/Card/index.module.scss
- src/components/Product/Card/index.tsx
- src/components/Product/MoreFromSeller/__tests__/index.test.tsx
- src/components/Product/MoreFromSeller/index.module.scss
- src/components/Product/MoreFromSeller/index.tsx
Jira: [AUCTO-16](https://auctomarket.atlassian.net/browse/AUCTO-16)
create MoreFromSeller component
> feat(AUCTO-16): create MoreFromSeller component

- src/components/Product/Card/index.module.scss
- src/components/Product/Recommended/__tests__/index.test.tsx
- src/components/Product/Recommended/index.module.scss
- src/components/Product/Recommended/index.tsx
This depends on https://github.com/AuctoMarket/BuyerMarketplace/pull/11
Jira: [AUCTO-20](https://auctomarket.atlassian.net/browse/AUCTO-20)
create Recommended for you component
> feat(AUCTO-20): create Recommended for you component

- src/components/Product/MoreFromSeller/index.module.scss
Jira: [AUCTO-16](https://auctomarket.atlassian.net/browse/AUCTO-16)
adjust MoreFromSeller product cards size on mobile
> feat(AUCTO-16): adjust MoreFromSeller product cards size on mobile

- src/components/Product/Card/__tests__/index.test.tsx
- src/components/Product/Card/index.tsx
- src/components/Product/MoreFromSeller/__tests__/index.test.tsx
- src/components/Product/MoreFromSeller/index.tsx
- src/components/Product/Recommended/__tests__/index.test.tsx
- src/components/Product/Recommended/index.tsx
- src/components/Product/SellerInfo/__tests__/index.test.tsx
- src/components/Product/SellerInfo/index.module.scss
- src/components/Product/SellerInfo/index.tsx
Jira: [AUCTO-28](https://auctomarket.atlassian.net/browse/AUCTO-28)
Change Seller num reviews to followers
> feat(AUCTO-28): Change Seller num reviews to followers

- src/components/Product/Card/__tests__/index.test.tsx
- src/components/Product/Card/index.module.scss
- src/components/Product/Card/index.tsx
- src/components/Product/MoreFromSeller/__tests__/index.test.tsx
- src/components/Product/MoreFromSeller/index.tsx
- src/components/Product/Recommended/__tests__/index.test.tsx
- src/components/Product/Recommended/index.tsx
Jira: [AUCTO-26](https://auctomarket.atlassian.net/browse/AUCTO-26)
Add Pre-Order badge to ProductCard component
> feat(AUCTO-26): Add Pre-Order badge to ProductCard component

- README.md
- package-lock.json
- package.json
- src/components/Product/Images/Mobile/__tests__/index.test.tsx
- src/components/Product/Images/Mobile/index.module.scss
- src/components/Product/Images/Mobile/index.tsx
- src/components/Product/Images/__tests__/index.test.tsx
- src/components/Product/Images/index.module.scss
- src/components/Product/Images/index.tsx
- src/components/Product/Recommended/index.module.scss
- tailwind.config.js
Jira: [AUCTO-10](https://auctomarket.atlassian.net/browse/AUCTO-10)
create Images components for Product page
> feat(AUCTO-10): create Images components for Product page

- .github/CODEOWNERS
Jira: [AUCTO-41](https://auctomarket.atlassian.net/browse/AUCTO-41)
add GitHub CODEOWNERS file
> feat(AUCTO-41): add GitHub CODEOWNERS file

- .github/workflows/codeql.yml
Jira: [AUCTO-42](https://auctomarket.atlassian.net/browse/AUCTO-42)
add CodeQL workflow
> feat(AUCTO-42): add CodeQL workflow

- src/components/LoginForm/__tests__/index.test.tsx
- src/components/LoginForm/index.module.scss
- src/components/LoginForm/index.tsx
- src/components/SignupForm/__tests__/index.test.tsx
- src/components/SignupForm/index.module.scss
- src/components/SignupForm/index.tsx
- src/pages/holding/index.tsx
click on the sign up link on the login popup to view
Jira: AUCTO-29
> feat(AUCTO-29): signup popup done

- src/components/Product/Recommended/__tests__/index.test.tsx
- src/components/Product/Recommended/index.module.scss
- src/components/Product/Recommended/index.tsx
- src/pages/product/index.tsx
Jira: [AUCTO-49](https://auctomarket.atlassian.net/browse/AUCTO-49)
update Recommended component for Homepage
> feat(AUCTO-49): update Recommended component for Homepage

- package-lock.json
- package.json
- src/components/Product/Card/Horizontal/__tests__/index.test.tsx
- src/components/Product/Card/Horizontal/index.module.scss
- src/components/Product/Card/Horizontal/index.tsx
- src/components/Product/HotDeals/__tests__/index.test.tsx
- src/components/Product/HotDeals/index.module.scss
- src/components/Product/HotDeals/index.tsx
- src/components/Product/PostedDate/__tests__/index.test.tsx
- src/components/Product/PostedDate/index.tsx
- src/index.tsx
- src/setupTests.ts
Jira: [AUCTO-48](https://auctomarket.atlassian.net/browse/AUCTO-48)
create HotDeals component
> feat(AUCTO-48): create HotDeals component

- src/components/Product/Card/__tests__/index.test.tsx
- src/components/Product/Card/index.tsx
- src/components/Product/Images/Mobile/__tests__/index.test.tsx
- src/components/Product/Images/Mobile/index.tsx
- src/components/Product/Images/__tests__/index.test.tsx
- src/components/Product/Images/index.tsx
- src/types/product.type.ts
- src/utils/__tests__/transformProduct.test.ts
- src/utils/transformProduct.ts
Jira: [AUCTO-56](https://auctomarket.atlassian.net/browse/AUCTO-56)
connect Product page to Product Images API
> feat(AUCTO-56): connect Product page to Product Images API

- src/components/Button/Link/__tests__/index.test.tsx
- src/components/Button/Link/index.module.scss
- src/components/Button/Link/index.tsx
- src/components/Product/Card/index.module.scss
- src/components/Product/Card/index.tsx
- src/components/Product/Details/index.module.scss
- src/components/Product/MoreFromSeller/index.module.scss
- src/components/Product/Purchase/Buy/__tests__/index.test.tsx
- src/components/Product/Purchase/Buy/index.tsx
- src/components/Product/RecentlyAdded/__tests__/index.test.tsx
- src/components/Product/RecentlyAdded/index.tsx
- src/components/Product/SellerInfo/InCard/__tests__/index.test.tsx
- src/components/Product/SellerInfo/InCard/index.module.scss
- src/components/Product/SellerInfo/InCard/index.tsx
- src/components/Product/SellerInfo/index.tsx
- src/pages/product/index.module.scss
- src/pages/product/index.tsx
- src/types/product.type.ts
Jira: AUCTO-66
Update Product page UI (2nd launch)
Check Netlify preview link https://deploy-preview-39--aucto.netlify.app/products/3003e1c8-37ff-11ee-b26e-0aec91b1c67e
> feat(AUCTO-66): update Product page UI (2nd launch)

- src/components/Header/__tests__/index.test.tsx
- src/components/Header/index.module.scss
- src/components/Header/index.tsx
- src/components/Layout/__tests__/index.test.tsx
Jira: [AUCTO-69](https://auctomarket.atlassian.net/browse/AUCTO-69)
update Header NavBar (2nd launch)
Check Netlify preview link https://deploy-preview-41--aucto.netlify.app/products/3003e1c8-37ff-11ee-b26e-0aec91b1c67e
> feat(AUCTO-69): update Header NavBar (2nd launch)

- src/components/Button/index.module.scss
- src/components/NumberInput/__tests__/index.test.tsx
- src/components/NumberInput/index.module.scss
- src/components/NumberInput/index.tsx
- src/components/Product/Images/Mobile/index.module.scss
- src/components/Product/Price/__tests__/index.test.tsx
- src/components/Product/Price/index.tsx
- src/components/Product/Purchase/Buy/index.module.scss
- src/components/Product/Purchase/Buy/index.tsx
- src/pages/product/index.tsx
Jira: AUCTO-82
add Quantity input to Product page & format price to have 2 decimals
> feat(AUCTO-82): add Quantity input to Product page

- src/components/Product/Promotion/index.module.scss
- src/components/Product/Promotion/index.tsx
- src/components/Product/RecentlyAdded/index.module.scss
- src/components/Sellers/Promotion/index.module.scss
- src/pages/home/index.module.scss
- src/pages/home/index.tsx
Jira: AUCTO-70
home page mobile version
Check Netlify preview link
> feat(AUCTO-70): home page mobile version

- src/components/Button/index.module.scss
- src/components/Button/index.tsx
- src/components/Checkout/ContactDetails/index.module.scss
- src/components/Checkout/DeliveryMethods/GroupButton/__test__/index.test.tsx
- src/components/Checkout/DeliveryMethods/GroupButton/index.module.scss
- src/components/Checkout/DeliveryMethods/GroupButton/index.tsx
- src/components/Checkout/DeliveryMethods/NormalDelivery/__test__/index.test.tsx
- src/components/Checkout/DeliveryMethods/NormalDelivery/index.module.scss
- src/components/Checkout/DeliveryMethods/NormalDelivery/index.tsx
- src/components/Checkout/DeliveryMethods/SelfCollection/__test__/index.test.tsx
- src/components/Checkout/DeliveryMethods/SelfCollection/index.module.scss
- src/components/Checkout/DeliveryMethods/SelfCollection/index.tsx
- src/components/Checkout/DeliveryMethods/__tests__/index.test.tsx
- src/components/Checkout/DeliveryMethods/index.module.scss
- src/components/Checkout/DeliveryMethods/index.tsx
- src/components/Checkout/SectionHeading/index.module.scss
- src/components/NumberInput/index.module.scss
- src/components/NumberInput/index.tsx
- src/types/checkout.type.ts
Jira: AUCTO-73
create DeliveryMethods component
> feat(AUCTO-73): create DeliveryMethods component

- src/components/Checkout/PaymentMethods/__tests__/index.test.tsx
- src/components/Checkout/PaymentMethods/index.module.scss
- src/components/Checkout/PaymentMethods/index.tsx
Jira: AUCTO-74
Create PaymentMethods component
> feat(AUCTO-74): create PaymentMethods component

- package.json
Jira: -
Configure lint-staged to format scss on commit
> ci(lint-staged): format scss on commit

- src/components/LoginForm/index.tsx
- src/components/Product/Purchase/Buy/index.tsx
Jira: AUCTO-XX
A few words about the issue...
Detailed steps for reviewers and QA
> feat(AUCTO-35): fixed signup when users click buy in product page

- public/index.css
Jira: AUCTO-89
A few words about the issue...
Detailed steps for reviewers and QA
> fix(AUCTO-89): wrong Lato-Semibold font url

- .github/workflows/codeql.yml
- .github/workflows/lint-build-test.yml
- package.json
> chore(ci): add release tool
